//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koshelevskaya_v6.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public int ServiceID { get; set; }
        public int ClientID { get; set; }
        public string ServiceName { get; set; }
        public string Description { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
